cboulay/PSMoveService

src/openvr_plugin/driver_psmoveservice.cpp, src/openvr_plugin/driver_psmoveservice.h
You can now assign PS Move buttons to act as directional presses on the PSMove touchpad. Add a structure like this to steamvr.vrsettings:
"psmove_touchpad_directions" : {
"circle" : "touchpad_right",
"cross" : "touchpad_left",
"select" : "touchpad_up",
"start" : "touchpad_down"
}
=> Button mappings for touchpad swipes

src/psmoveservice/Device/View/ServerTrackerView.cpp, src/psmoveservice/PSMoveTracker/PSEye/PSEyeVideoCapture.cpp
on my tests with delay_thread=0 to see higher utilisation I went down
from 53 to 48 % of cpu utilisation on 4eye3controler setup
i don't think it should be parametrized cause it is really easy to verify by few people and we should simply forget old code.
=> make camera flip image instead of code to save some cpu

src/tests/test_camera.cpp
This doesn't affect anything, but thought I'd point out that empty() is being used where clear() is probably the intention.
=> vector::empty being used instead of vector::clear

src/psmoveservice/PSNaviController/PSNaviController.cpp
I just spotted this while going through the code.
PSNAVI_BTADDR_SET_SIZE is 7.
in setHostBluetoothAddress() you have:
unsigned char bts[PSNAVI_BTADDR_SET_SIZE];
unsigned char addr[6];
memcpy(&bts[3], addr, sizeof(addr));
which means you're copying 6 bytes into position 4 of a 7 byte buffer.
I'm not terribly sure that this is the right way of "fixing" this, but something needs to change.
=> PSNaviController buffer overrun fix

src/psmoveclient/ClientControllerView.cpp, src/psmoveservice/Device/Manager/TrackerManager.cpp, src/psmoveservice/Device/Manager/TrackerManager.h, src/psmoveservice/Device/View/ServerControllerView.cpp
* added ignore_pose_from_one_tracker parameter to tell if service should calculate pose from one controller, useful in 3+ tracker setup
* GetIsPoseValid() in client dll is also checking if pose if valid for ps move
=> added ignore_pose_from_one_tracker and extended check for GetIsPoseValid() in client dll

src/psmoveconfigtool/AppStage_ColorCalibration.cpp, src/psmoveconfigtool/AppStage_ColorCalibration.h, src/psmoveprotocol/PSMoveProtocol.proto, src/psmoveservice/Device/Interface/DeviceInterface.h, src/psmoveservice/Device/Manager/TrackerManager.cpp, src/psmoveservice/Device/Manager/TrackerManager.h, src/psmoveservice/Device/View/ServerTrackerView.cpp, src/psmoveservice/Device/View/ServerTrackerView.h, src/psmoveservice/PSMoveTracker/PS3EyeTracker.cpp, src/psmoveservice/PSMoveTracker/PS3EyeTracker.h, src/psmoveservice/PSMoveTracker/PSEye/PSEyeVideoCapture.cpp, src/psmoveservice/Server/ServerRequestHandler.cpp, src/tests/test_camera.cpp
Updated to the current master of PS3EYEDriver and added the ability to set the frame rate of
each camera. The frame rates are now stored in the configuration files and can be configured
using PSMoveConfigTool (changed the UI window sizes accordingly). test_camera also has the
ability to change the frame rate of the opened cameras with the y and h keys and check the
current setting with the space bar. The initialisation frame rate was changed to 15 fps from
60 fps to avoid bandwidth issues at the start.
(I actually seemed to do a rebase successfully this time.)
=> Added the ability to set the frame rate

src/openvr_plugin/driver_psmoveservice.cpp
@HipsterSloth Before you do another release here's a fix for the icons. What your friend said about setting the icons as “{psmove}iconname.png” was the fix.
=> Fixed SteamVR icons for OpenVR SDK 1.0.6

src/tests/CMakeLists.txt, src/tests/test_camera_parallel.cpp
The cameras are now operated in parallel so that they can have
completely independent frame rates (entered by the user at the
start). Previously it was limited by the slowest rate. All other settings
are also unique to each camera and can be set by clicking on it's window
and a list of the controls is given after entering the frame rates.
The camera limit has been raised to 30 for experimentation.
The parallelisation was done by using a large `concurrency::parallel_for_each` 
after opening the cameras instead of using an `std::for_each` at each step.
=> Added a parallel version of test_camera

src/psmoveconfigtool/AppStage_ColorCalibration.cpp, src/psmoveconfigtool/AppStage_ColorCalibration.h, src/psmoveconfigtool/AppStage_TrackerSettings.cpp, src/psmoveconfigtool/AppStage_TrackerSettings.h
There are now automation options for changing the colour, controller and
tracker after setting the colour preset with a right-click. The automation
is prioritised as colour then controller then tracker. When cycling
through the colours the presets are automatically saved (the controller
and mouse must remain overlapped to be succesful).
Buttons have also been added to the colour configuration window to be able
to manually cycle through the controllers and trackers with out leaving
the window. A main menu button has also been added. The trailing zeros of
the frame rate, exposure and gain have been removed.
The buttons for changing the tracker in the tracker setting window are now
looped such that the first and last trackers can be switch to from one
another with a single click.
I think …
=> Added a semi-automatic colour calibration

src/psmoveclient/ClientPSMoveAPI.cpp, src/psmoveclient/ClientPSMoveAPI.h, src/psmoveclient/PSMoveClient_CAPI.cpp, src/psmoveclient/PSMoveClient_CAPI.h, src/psmoveconfigtool/AppStage_ColorCalibration.cpp, src/psmoveconfigtool/AppStage_ComputeTrackerPoses.cpp, src/psmoveconfigtool/AppStage_DistortionCalibration.cpp, src/psmoveconfigtool/AppStage_HMDModelCalibration.cpp, src/psmoveconfigtool/AppStage_TestTracker.cpp, src/psmoveprotocol/PSMoveProtocol.proto, src/psmoveprotocol/ProtocolVersion.h, src/psmoveservice/Device/View/ServerTrackerView.cpp, src/psmoveservice/Device/View/ServerTrackerView.h, src/psmoveservice/Server/ServerRequestHandler.cpp
I think I've successfully reverted the commit that added flags to the debug overlay.
Now the cross hairs shrink with the ellipse or rectangle that they are drawn in. I couldn't reduce the thickness as they were already set to the minimum but I think it looks okay.
=> Shrink cross hairs instead of removing them completely

src/tests/test_camera.cpp
People were not realising that the initial frame rate was 15 fps rather
than the values set by the config files. To overcome this the initial
frame rate must now be specified by the user at the start.
Chris warned me that this may be the case so I put the user prompt in 
the parallel version but not the normal one to keep it simple. This was,
as it turns out, a mistake.
=> Added instructions and a user prompt for the frame rate

src/psmoveconfigtool/AppStage_ColorCalibration.cpp, src/psmoveconfigtool/AppStage_ColorCalibration.h
In some circumstances the setting windows may hide the controller or other
detected objects. To overcome this the windows can now be hidded by
pressing the space bar. Since this then removes direct access to some of
the funtions (like changing the filter) keyboard shortcuts have been added
to the more important ones (the letter used has been placed in square brackets).
=> Added the option to hide the setting windows during colour calibration

src/openvr_plugin/driver_psmoveservice.cpp, src/openvr_plugin/driver_psmoveservice.h
Added a section to steamvr.vrsettings for controller specific button
mapping based on the controller's Id (eg. add "_0" to the "psmove" section to
make it controller 0 specific). This also applies to the touchpad section
psmove_touchpad_directions. Coding the Id int to convert into a char was
problematic so it was done using if statements for values 0 to 9.
The controller Id parameter was added to the end of LoadButtonMapping with
a default value of -1 so that if it is not specified this new mapping
feature will be ignored. It is also ignored for Ids larger than 9.
=> Added controller specific SteamVR button mapping

src/openvr_plugin/driver_psmoveservice.cpp, src/openvr_plugin/driver_psmoveservice.h
If the PSMove controller has a PSNavi child the recenter function of the
SELECT button is overrode by the D-pad down button of the PSNavi
controller. This makes it easier to access if the PSMove is paired with 
a PSNavi.
I'm not sure whether this should be merged as it is because it is not user 
adjustable. Since the PSNavi doesn't have any hard to reach buttons like 
the SELECT button would it be better to increase the required hold time 
for the PSNavi button mode?
=> Changed recenter controller button to Navi D-pad down if the PSMove has a PSNavi child

src/psmoveconfigtool/AppStage_AccelerometerCalibration.cpp
The acceleration vector was not properly set for the world view mode
of test accelerometer in the config tool. It had to be rotated by -90
deg (ie. oposite to how the defaultControllerTransform is set for the
PSMove controller model). The acceleration vector now always points up if
the controller is at rest in the world's frame of reference.
=> Rotated acceleration vector for world view of test accelerometer

src/openvr_plugin/driver_psmoveservice.cpp, src/psmoveclient/ClientControllerView.h, src/psmoveclient/PSMoveClient_CAPI.cpp
The TriggerValue for the PSMove and PSNavi were getting converted back
and forth between an unsigned char and a normalised float. To make it
simpler keep it as an unsigned char untill it needs to be read by a
program at which point it can be converted.
This will probably cause a problem for the PSMoveFreepieBridge but that
will need to be ungraded for the CAPI anyway.
=> Keep TriggerValue an unsigned char untill it is used

src/openvr_plugin/driver_psmoveservice.cpp, src/psmoveclient/ClientPSMoveAPI.h, src/psmoveclient/ClientRequestManager.cpp, src/psmoveclient/PSMoveClient_CAPI.h, src/psmoveservice/Device/View/ServerControllerView.cpp
Previously only one serial number was kept in the list (it wasn't an
actual list). This was the case for both the controller_serial list and
the parent_controller_serial list.
The PSNavi child check was also fixed. It was checking if it was a
PSMove instead of a PSNavi.
=> Fixed the serial number handling

src/openvr_plugin/driver_psmoveservice.cpp, src/openvr_plugin/driver_psmoveservice.h
The button mapping options for the touchpad directions was limited to
up/down/left/right. This adds the diagonal combinations as possible
mapping options.
=> Added the option to assign a button to the diagonals of the touchpad

src/psmoveconfigtool/AppStage_ColorCalibration.cpp, src/psmoveconfigtool/AppStage_ColorCalibration.h, src/psmoveconfigtool/AppStage_TrackerSettings.cpp, src/psmoveconfigtool/AppStage_TrackerSettings.h, src/psmoveprotocol/PSMoveProtocol.proto, src/psmoveservice/Device/Interface/DeviceInterface.h, src/psmoveservice/Device/Manager/TrackerManager.cpp, src/psmoveservice/Device/Manager/TrackerManager.h, src/psmoveservice/Device/View/ServerTrackerView.cpp, src/psmoveservice/Device/View/ServerTrackerView.h, src/psmoveservice/PSMoveTracker/PS3EyeTracker.cpp, src/psmoveservice/PSMoveTracker/PS3EyeTracker.h, src/psmoveservice/PSMoveTracker/PSEye/PSEyeVideoCapture.cpp, src/psmoveservice/Server/ServerRequestHandler.cpp, src/tests/test_camera.cpp, src/tests/test_camera_parallel.cpp
Added control over the PSEye frame width and height. Since they are
linked only the width is specified in the configuration files but both
are available to be changed. They have been implemented similar to the
frame rate. The frame rate calls have been slightly changed so that they
match the frame width and height (ie. Framerate has been renamed FrameRate).
When changing the frame resolution the buffer is closed and reopened by
ServerTrackerView so that it has the correct size. This causes the video
feed in Color calibration to freeze so it is automatically exited and
reopened.
The QVGA resolution may be useful for the position triangulation method
if more than four cameras are used.
This currently uses my fork of PS3EYEDriver but I've already made a PR for it …
=> Add PSEye resolution control

src/openvr_plugin/driver_psmoveservice.cpp
The ready icon was switched for the ready_alert one.
The icon paths now don't get used so are now redundant and have been
removed.
=> Fixed SteamVR tracker icon

src/psmoveconfigtool/AppStage_ColorCalibration.cpp, src/psmoveconfigtool/AppStage_ColorCalibration.h
To help in aligning the trackers, an optional alignment marker has
been added to the Calibrate Controller Tracking Colours window. This
marker can be accessed by pressing the X key and has two modes (cycled
with the X key). The first mode uses a black cross to mark the absolute
center. The second mode uses the color oposite to the current orb color.
=> Added an optinal alignment marker to the colour calibration window

src/psmoveconfigtool/AppStage_ColorCalibration.cpp, src/psmoveconfigtool/AppStage_ColorCalibration.h, src/psmoveconfigtool/AppStage_ComputeTrackerPoses.cpp, src/psmoveconfigtool/AppStage_ComputeTrackerPoses.h
* Since the position of the orb is the same for all trackers when using
the alignment marker, this position can be used instead of the mouse
position. This also alows the calibration to continue uninterupted when
the tracker is changed. Auto controller switching however is then disabled.
* The surface used to place the controller on may not be vertically
centered (such as the floor) so the marker can now be moved up and down
using the W and S keys and recentered with the Z key.
* A similar marker has also been added to the verification step of the
tracker pose calibration but only has a black cross and it's vertical
position isn't synced with the other marker.
=> Integrate the alignment marker into the auto colour calibration

src/psmoveclient/PSMoveClient_CAPI.cpp, src/psmoveconfigtool/AppStage_ComputeTrackerPoses.cpp
* For #411 added a check to find if the current tracker is in the
controller's tracker list.
* The controller stability check was not working. The angle calculation
was incomplete but is now fixed.
* Switching between test tracking and colour calibration did not always
remember which tracker was currently selected but it now does.
=> Fix for #411 and others

src/psmoveconfigtool/AppStage_TestRumble.cpp, src/psmoveconfigtool/AppStage_TestRumble.h
The rumble now turns off if it was on when leaving the test rumble menu.
=> Fix for #255

src/psmoveservice/Device/Interface/DeviceInterface.h
VirtualController was previously showing as "UNKNOWN".
=> Added VirtualController to the list of device types in the DeviceTypeManager

src/psmoveclient/ClientConstants.h, src/psmoveclient/PSMoveClient.cpp, src/psmoveclient/PSMoveClient_CAPI.h, src/psmoveconfigtool/AppStage_ControllerSettings.cpp, src/psmoveconfigtool/AppStage_ControllerSettings.h, src/psmoveconfigtool/psmove_config_tool.cpp, src/psmoveprotocol/PSMoveProtocol.proto, src/psmoveservice/Device/Interface/DeviceInterface.h, src/psmoveservice/Device/Manager/ControllerManager.cpp, src/psmoveservice/Device/Manager/ControllerManager.h, src/psmoveservice/Device/Manager/DeviceManager.cpp, src/psmoveservice/Device/View/ServerControllerView.cpp, src/psmoveservice/Server/ServerRequestHandler.cpp, src/psmoveservice/VirtualController/VirtualController.cpp, src/psmoveservice/VirtualController/VirtualController.h
There are now two new options in the virtual controller settings UI:
* Assigned Gamepad - Allows you to assign a gamepad to a virtual controller
* Test Buttons - A screen for testing buttons and axis on a controller
The "Test Buttons" screen is available for all controller types (PSMove, PSNavi, DualShock 4, and Virtual Controllers). For the PSMove controller it looks like this:
For virtual controllers, buttons are mapped from the selected gamepad connected to the PC. The gamepad must support the XInput API on Win10 (xbox 360 controllers being one example). Since there is no context for what the buttons and axes are from the gamepad API you'll just get a generic button and axis list. It's up to users of the PSMove client API to map buttons to a desired action. 
The key take away from this …
=> Adding gamepad assignment to VirtualControllers

src/psmoveclient/PSMoveClient_CAPI.cpp, src/psmoveconfigtool/AppStage_ComputeTrackerPoses.cpp, src/psmoveconfigtool/AppStage_ComputeTrackerPoses.h, src/psmoveconfigtool/AppStage_TrackerSettings.cpp, src/psmoveconfigtool/AppSubStage_CalibrateWithMat.cpp, src/psmoveconfigtool/AppSubStage_CalibrateWithMat.h, src/psmoveprotocol/ProtocolVersion.h
* Useful if you only have a virtual HMD to use
* Don't consider virtual HMDs or virtual Controllers ever stable (always use "Trust me, it's stable button")
* Updating AppSubStage_CalibrateWithMat to work with both controllers and HMDs
=> Fixing tracker pose calibration to support calibration with HMDs

src/psmoveconfigtool/AppStage_TrackerSettings.cpp, src/psmoveservice/Device/Enumerator/ControllerGamepadEnumerator.cpp, src/psmoveservice/Device/Enumerator/ControllerGamepadEnumerator.h, src/psmoveservice/Device/Manager/ControllerManager.cpp
Don't enumerate over PSNavi controllers when virtual controllers are active
* No easy way to distinguish between navi controllers and other XInput controllers
* Navi gets treated as a virtual controller in this case
Fixed typo in Tracker Settings UI
=> Assorted virtual controller work related fixes

src/psmoveservice/Device/Enumerator/ControllerGamepadEnumerator.cpp
Allow the PSNavi to be Enumerated when there are no virtual controllers.
=> Fixed PSNavi Enumeration

src/psmoveclient/ClientConstants.h, src/psmoveprotocol/PSMoveProtocolInterface.h, src/psmoveservice/Device/Manager/ControllerManager.h, src/psmoveservice/Device/Manager/DeviceTypeManager.h, src/psmoveservice/Device/Manager/HMDManager.h, src/psmoveservice/Device/Manager/TrackerManager.h
The tracker limit was independently defined in two locations. Now it is
controlled by just the one variable (PSMOVESERVICE_MAX_TRACKER_COUNT).
=> Unify some limit variables
